-- Complete 2026 CUBSO segment catalog used to validate onboarding suggestions.
-- Operational ingestion scope remains controlled by mvp_enabled_cubso_segments.
INSERT INTO cat_cubso_segmentos (codigo, anio, nombre, raw_json, synced_at)
VALUES
  ('10', 2026, 'Material, accesorios y suministros de plantas y animales vivos', '{}'::jsonb, now()),
  ('11', 2026, 'Materiales de minerales, tejidos, plantas y animales no comestibles', '{}'::jsonb, now()),
  ('12', 2026, 'Productos químicos, bio-químicos y gases industriales', '{}'::jsonb, now()),
  ('13', 2026, 'Resina, colofonia, caucho, espuma y materiales elastoméricos', '{}'::jsonb, now()),
  ('14', 2026, 'Productos de papel y materiales', '{}'::jsonb, now()),
  ('15', 2026, 'Combustibles, aditivos para combustibles, lubricantes y materiales anticorrosivos', '{}'::jsonb, now()),
  ('20', 2026, 'Maquinaria y accesorios para perforación de pozos y minería', '{}'::jsonb, now()),
  ('21', 2026, 'Maquinaria y accesorios para agricultura, pesca, silvicultura y fauna', '{}'::jsonb, now()),
  ('22', 2026, 'Maquinaria y accesorios para construcción y edificación', '{}'::jsonb, now()),
  ('23', 2026, 'Maquinaria y accesorios de fabricación y transformación industrial', '{}'::jsonb, now()),
  ('24', 2026, 'Maquinaria, accesorios y suministros para manejo, acondicionamiento y almacenamiento de materiales', '{}'::jsonb, now()),
  ('25', 2026, 'Vehículos, accesorios y componentes', '{}'::jsonb, now()),
  ('26', 2026, 'Maquinaria y accesorios para generación y distribución de energía', '{}'::jsonb, now()),
  ('27', 2026, 'Herramientas y maquinaria en general', '{}'::jsonb, now()),
  ('30', 2026, 'Componentes y suministros de construcciones, estructuras y obras', '{}'::jsonb, now()),
  ('31', 2026, 'Componentes y suministros de fabricación', '{}'::jsonb, now()),
  ('32', 2026, 'Componentes y suministros electrónicos', '{}'::jsonb, now()),
  ('39', 2026, 'Suministros, componentes y accesorios eléctricos y de iluminación', '{}'::jsonb, now()),
  ('40', 2026, 'Componentes, equipos y sistemas de acondicionamiento y de distribución', '{}'::jsonb, now()),
  ('41', 2026, 'Equipo de laboratorio, medición, observación y comprobación', '{}'::jsonb, now()),
  ('42', 2026, 'Equipos, accesorios y suministros médicos', '{}'::jsonb, now()),
  ('43', 2026, 'Telecomunicaciones, radiodifusión y tecnología de la información', '{}'::jsonb, now()),
  ('44', 2026, 'Equipo, accesorios y suministros de oficina', '{}'::jsonb, now()),
  ('45', 2026, 'Equipo y suministros fotográficos, audiovisuales y de impresión', '{}'::jsonb, now()),
  ('46', 2026, 'Aplicación de la ley y seguridad nacional: equipos, suministros de seguridad y protección', '{}'::jsonb, now()),
  ('47', 2026, 'Suministros y equipo de Limpieza', '{}'::jsonb, now()),
  ('48', 2026, 'Maquinaria, equipo y suministros para la industria de servicios', '{}'::jsonb, now()),
  ('49', 2026, 'Accesorios, suministros y equipos recreativos y deportivos', '{}'::jsonb, now()),
  ('50', 2026, 'Alimentos y bebidas para consumo humano', '{}'::jsonb, now()),
  ('51', 2026, 'Productos farmacéuticos incluidos anticonceptivos y vacunas', '{}'::jsonb, now()),
  ('52', 2026, 'Electrodomésticos, productos electrónicos, enseres, ropa de cama, toallas y otros accesorios', '{}'::jsonb, now()),
  ('53', 2026, 'Productos para el cuidado personal, equipaje y vestimenta', '{}'::jsonb, now()),
  ('54', 2026, 'Productos de piedras preciosas, joyas y relojes', '{}'::jsonb, now()),
  ('55', 2026, 'Productos publicados', '{}'::jsonb, now()),
  ('56', 2026, 'Muebles y mobiliario', '{}'::jsonb, now()),
  ('60', 2026, 'Instrumentos Musicales, Juegos, Juguetes, Arte y Equipo Educativo', '{}'::jsonb, now()),
  ('70', 2026, 'Servicios de contratación agrícola, pesquera, forestal y de fauna', '{}'::jsonb, now()),
  ('71', 2026, 'Servicios de minería, petroleo y gas', '{}'::jsonb, now()),
  ('72', 2026, 'Servicios de construcción y mantenimiento de instalaciones y edificios', '{}'::jsonb, now()),
  ('73', 2026, 'Servicios de fabricación y producción industrial', '{}'::jsonb, now()),
  ('76', 2026, 'Servicios de limpieza industrial', '{}'::jsonb, now()),
  ('77', 2026, 'Servicios medioambientales', '{}'::jsonb, now()),
  ('78', 2026, 'Servicios de transporte, almacenamiento y correspondencia', '{}'::jsonb, now()),
  ('80', 2026, 'Servicios profesionales de gestión, negocios y servicios administrativos', '{}'::jsonb, now()),
  ('81', 2026, 'Servicios en Ingeniería e investigación y servicios basados en tecnología', '{}'::jsonb, now()),
  ('82', 2026, 'Servicios de edición, diseño y artes gráficas', '{}'::jsonb, now()),
  ('83', 2026, 'Servicios públicos y servicios relacionados con el sector público', '{}'::jsonb, now()),
  ('84', 2026, 'Servicios financieros y de seguros', '{}'::jsonb, now()),
  ('85', 2026, 'Servicio de atención médica', '{}'::jsonb, now()),
  ('86', 2026, 'Servicios educativos y de capacitación', '{}'::jsonb, now()),
  ('90', 2026, 'Servicios de viaje, alimentación, alojamiento y entretenimiento', '{}'::jsonb, now()),
  ('91', 2026, 'Servicios personales y domésticos', '{}'::jsonb, now()),
  ('92', 2026, 'Servicios de Orden Público, Seguridad y Vigilancia', '{}'::jsonb, now()),
  ('93', 2026, 'Servicios políticos y de asuntos cívicos', '{}'::jsonb, now()),
  ('94', 2026, 'Organizaciones y clubes', '{}'::jsonb, now()),
  ('95', 2026, 'Terreno, edificios, estructuras y vías principales', '{}'::jsonb, now())
ON CONFLICT (codigo, anio) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  synced_at = EXCLUDED.synced_at;
